/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatJoinRouteImport } from './routes/chat/join'
import { Route as ChatHostRouteImport } from './routes/chat/host'
import { Route as ChatChatroomIdRouteImport } from './routes/chat/$chatroomId'

const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatJoinRoute = ChatJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ChatRoute,
} as any)
const ChatHostRoute = ChatHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => ChatRoute,
} as any)
const ChatChatroomIdRoute = ChatChatroomIdRouteImport.update({
  id: '/$chatroomId',
  path: '/$chatroomId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/share': typeof ShareRoute
  '/chat/$chatroomId': typeof ChatChatroomIdRoute
  '/chat/host': typeof ChatHostRoute
  '/chat/join': typeof ChatJoinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/share': typeof ShareRoute
  '/chat/$chatroomId': typeof ChatChatroomIdRoute
  '/chat/host': typeof ChatHostRoute
  '/chat/join': typeof ChatJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/receive': typeof ReceiveRoute
  '/share': typeof ShareRoute
  '/chat/$chatroomId': typeof ChatChatroomIdRoute
  '/chat/host': typeof ChatHostRoute
  '/chat/join': typeof ChatJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/receive'
    | '/share'
    | '/chat/$chatroomId'
    | '/chat/host'
    | '/chat/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/receive'
    | '/share'
    | '/chat/$chatroomId'
    | '/chat/host'
    | '/chat/join'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/receive'
    | '/share'
    | '/chat/$chatroomId'
    | '/chat/host'
    | '/chat/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  ReceiveRoute: typeof ReceiveRoute
  ShareRoute: typeof ShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/join': {
      id: '/chat/join'
      path: '/join'
      fullPath: '/chat/join'
      preLoaderRoute: typeof ChatJoinRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/host': {
      id: '/chat/host'
      path: '/host'
      fullPath: '/chat/host'
      preLoaderRoute: typeof ChatHostRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$chatroomId': {
      id: '/chat/$chatroomId'
      path: '/$chatroomId'
      fullPath: '/chat/$chatroomId'
      preLoaderRoute: typeof ChatChatroomIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatroomIdRoute: typeof ChatChatroomIdRoute
  ChatHostRoute: typeof ChatHostRoute
  ChatJoinRoute: typeof ChatJoinRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatroomIdRoute: ChatChatroomIdRoute,
  ChatHostRoute: ChatHostRoute,
  ChatJoinRoute: ChatJoinRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  ReceiveRoute: ReceiveRoute,
  ShareRoute: ShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
